syntax on
set smartindent
set tabstop=4
set expandtab
set shiftwidth=4
set number
set relativenumber
set ruler
set hlsearch
set splitright
command T vert term
tab all
inoremap jk <Esc>
inoremap kj <Esc>
nnoremap <C-S> :w \| !clear && pypy3 % < %:r.eg && echo "-----------" && pypy3 % < %:r.in<CR>
nnoremap <Esc><C-S> :w \| !clear && pypy3 % < %:r.eg<CR>
nnoremap n nzz
nnoremap N Nzz
